require("settings.keys")
require("settings.lazy")
require("settings.set")
require("settings.color")
require("settings.conform")
require("settings.gitsigns")
require("settings.hlargs")
require("settings.mini")
require("settings.telescope")
require("settings.treesitter")
require("settings.langservers")
vim.g.codeium_enabled = false
