require("settings.keys")
require("settings.plugins")
require("settings.set")
require("settings.color")
-- require("settings.cmp")
require("settings.conform")
-- require("settings.dap")
require("settings.gitsigns")
require("settings.hlargs")
require("settings.mini")
require("settings.telescope")
require("settings.treesitter")
require("settings.langservers")
